version: 2
builds:
  - id: "ghq-fzf"
    builder: bun
    binary: _ghq-fzf
    main: "cli.ts"
    flags:
      - --minify
      - --compile
      - --sourcemap
brews:
  - name: ghq-fzf
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    license: "MIT"
    install: |
      bin.install "_ghq-fzf"
    repository:
      owner: yumafuu
      name: homebrew-tap
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
