name: release

on:
  push:
    tags:
      - "v*"

jobs:
  compile:
    name: Release Packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - linux-x64
          - linux-arm64
          - darwin-x64
          - darwin-arm64
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Compile
        run: |
          bun i && bun build  --compile --minify --sourcemap ./cli.ts --target=bun-${{ matrix.target }} --outfile ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: ${{ matrix.target }}

  release:
    name: Release Packages
    runs-on: ubuntu-latest
    needs:
      - compile
    steps:
      - uses: actions/checkout@v4

      - { uses: actions/download-artifact@v4, with: { name: linux-x64,     path: release/ } }
      - { uses: actions/download-artifact@v4, with: { name: linux-arm64,   path: release/ } }
      - { uses: actions/download-artifact@v4, with: { name: darwin-x64,    path: release/ } }
      - { uses: actions/download-artifact@v4, with: { name: darwin-arm64,  path: release/ } }

      - name: DEBUG
        run: |
          ls -la release/

      - name: DEBUG
        run: |
          ls -la release/

      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: release/
          GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
